language: node_js
node_js:
  - 12.10.0

install:
  - cd App/backend/
  - npm install 
  - npm install node-sass
  - npm audit fix

script:
  - npm run test

after_success:
  - cd ../../
  - ls -al
  - mkdir code_deploy_artificats
  - ls -al
  - zip -r smart_events_backend_zip.zip App/backend *.sh *.yml
  - mv smart_events_backend_zip.zip code_deploy_artificats/
  - cd code_deploy_artificats
  - ls -al

deploy:
  - provider: s3
    local_dir: code_deploy_artificats
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
        all branches: true

  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $s3_bucket
    key: smart_events_backend_zip.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      all branches: true