version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: ./App_spec_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: ./App_spec_scripts/change_permissions.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./App_spec_scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: ./App_spec_scripts/stop_server.sh
      timeout: 300
      runas: ec2-user